# Title to use for the report.
# title: "AbPreP MultiQC Report"

# Set module order
module_order:
  - "samtools"
  - "read_length"
  - "matchbox"
  - "riot"

# Clean up file name extensions
extra_fn_clean_exts:
  - "_alignment_stats"
  - "_matchbox_counts"
  - "_flagstat"
  - "_stats"
  - "_read_lengths"

# Ignore these files / directories / paths when searching for logs
fn_ignore_dirs:
  - combined_reads
  - all

# Remove module sections
remove_sections:
  - samtools-stats
  - samtools-flagstat
  - samtools-flagstat-pct

# Modify general stats table columns
general_stats_columns:
  samtools:
    columns:
      error_rate:
        hidden: true
      non_primary_alignments:
        hidden: true
      mapped_passed:
        hidden: true
      raw_total_sequences:
        hidden: false
      reads_mapped:
        hidden: false
      reads_mapped_percent:
        hidden: false

# Reorder column table placements
table_columns_placement:
  general_stats_table_table:
    raw_total_sequences: 1

# Modify read count format
read_count_multiplier: 1
read_count_prefix: ""

custom_plot_config:
  samtools_alignment_plot:
    title: "Samtools: Alignment Scores"